import type { WorkflowView, WorkflowsPage } from "./workflowsTypes";

const DEVELOPMENT_WORKFLOWS: WorkflowView[] = [
  {
    workflowId: "wf-sec-scan",
    name: "Continuous Compliance Check",
    description:
      "Scans backend services for vulnerable dependencies, triages findings, and prepares remediation tasks.",
    projectId: "proj-core-api",
    status: "running",
    paused: false,
    progress: { completed: 2, total: 4, failed: 0, blocked: 0, fraction: 0.5 },
    currentSpecId: "triage-findings",
    pendingApprovals: 0,
    participatingAgents: ["research", "developer", "qa"],
    stages: [
      {
        specId: "inventory-dependencies",
        type: "research",
        description: "Inventory dependencies across all backend services.",
        status: "completed",
        assignedAgentId: "research",
        retryCount: 0,
      },
      {
        specId: "scan-cves",
        type: "research",
        description: "Match inventory against known CVE advisories.",
        status: "completed",
        assignedAgentId: "research",
        retryCount: 1,
      },
      {
        specId: "triage-findings",
        type: "development",
        description: "Triage findings and propose dependency upgrades.",
        status: "dispatched",
        assignedAgentId: "developer",
        retryCount: 0,
      },
      {
        specId: "verify-upgrades",
        type: "qa",
        description: "Verify proposed upgrades against the test suite.",
        status: "pending",
        retryCount: 0,
      },
    ],
    startedAt: "2026-09-12T14:30:00Z",
    updatedAt: "2026-09-12T15:45:00Z",
  },
  {
    workflowId: "wf-release-notes",
    name: "Release Notes Preparation",
    description:
      "Collects merged changes, drafts release notes, and routes them for operator approval before publishing.",
    projectId: "proj-money-mind",
    status: "awaiting_approval",
    paused: false,
    progress: { completed: 2, total: 3, failed: 0, blocked: 0, fraction: 0.67 },
    currentSpecId: "publish-notes",
    pendingApprovals: 1,
    participatingAgents: ["project-manager", "research"],
    stages: [
      {
        specId: "collect-changes",
        type: "research",
        description: "Collect merged changes since the previous release.",
        status: "completed",
        assignedAgentId: "research",
        retryCount: 0,
      },
      {
        specId: "draft-notes",
        type: "planning",
        description: "Draft user-facing release notes.",
        status: "completed",
        assignedAgentId: "project-manager",
        retryCount: 0,
      },
      {
        specId: "publish-notes",
        type: "planning",
        description: "Publish release notes (requires approval).",
        status: "awaiting_approval",
        assignedAgentId: "project-manager",
        retryCount: 0,
      },
    ],
    startedAt: "2026-09-11T09:00:00Z",
    updatedAt: "2026-09-12T11:20:00Z",
  },
  {
    workflowId: "wf-onboarding-audit",
    name: "Onboarding Flow Audit",
    description: "Reviews the onboarding flow for regressions after the latest UI changes.",
    projectId: "proj-money-mind",
    status: "running",
    paused: true,
    pauseReason: "Paused by operator while the staging environment is rebuilt.",
    progress: { completed: 1, total: 3, failed: 0, blocked: 0, fraction: 0.33 },
    currentSpecId: "run-regression",
    pendingApprovals: 0,
    participatingAgents: ["qa"],
    stages: [
      {
        specId: "map-flow",
        type: "qa",
        description: "Map onboarding screens and expected transitions.",
        status: "completed",
        assignedAgentId: "qa",
        retryCount: 0,
      },
      {
        specId: "run-regression",
        type: "qa",
        description: "Run regression checks against staging.",
        status: "ready",
        assignedAgentId: "qa",
        retryCount: 0,
      },
      {
        specId: "report-findings",
        type: "qa",
        description: "Summarise findings for the product team.",
        status: "pending",
        retryCount: 0,
      },
    ],
    startedAt: "2026-09-10T08:15:00Z",
    updatedAt: "2026-09-11T17:05:00Z",
  },
  {
    workflowId: "wf-data-migration",
    name: "Ledger Schema Migration Plan",
    description: "Plans and validates the migration of ledger tables to the new schema.",
    projectId: "proj-core-api",
    status: "failed",
    paused: false,
    progress: { completed: 1, total: 3, failed: 1, blocked: 1, fraction: 0.33 },
    pendingApprovals: 0,
    participatingAgents: ["developer", "qa"],
    stages: [
      {
        specId: "plan-migration",
        type: "development",
        description: "Draft the migration plan and rollback steps.",
        status: "completed",
        assignedAgentId: "developer",
        retryCount: 0,
      },
      {
        specId: "dry-run",
        type: "development",
        description: "Dry-run the migration against a snapshot.",
        status: "failed",
        assignedAgentId: "developer",
        retryCount: 2,
        error: "Snapshot restore timed out after 3 attempts.",
      },
      {
        specId: "validate-migration",
        type: "qa",
        description: "Validate row counts and invariants after migration.",
        status: "blocked",
        retryCount: 0,
      },
    ],
    startedAt: "2026-09-09T13:00:00Z",
    updatedAt: "2026-09-09T16:40:00Z",
    error: "Stage 'dry-run' exhausted its retry budget.",
  },
  {
    workflowId: "wf-weekly-digest",
    name: "Weekly Workforce Digest",
    description: "Summarises completed work and open risks for the weekly operator review.",
    projectId: "proj-core-api",
    status: "completed",
    paused: false,
    progress: { completed: 2, total: 2, failed: 0, blocked: 0, fraction: 1 },
    pendingApprovals: 0,
    participatingAgents: ["project-manager"],
    stages: [
      {
        specId: "gather-activity",
        type: "planning",
        description: "Gather task and workflow activity for the week.",
        status: "completed",
        assignedAgentId: "project-manager",
        retryCount: 0,
      },
      {
        specId: "write-digest",
        type: "planning",
        description: "Write the digest and highlight open risks.",
        status: "completed",
        assignedAgentId: "project-manager",
        retryCount: 0,
      },
    ],
    startedAt: "2026-09-08T07:00:00Z",
    updatedAt: "2026-09-08T07:42:00Z",
    completedAt: "2026-09-08T07:42:00Z",
  },
];

export function getDevelopmentWorkflowsFallback(): WorkflowsPage {
  return {
    items: DEVELOPMENT_WORKFLOWS,
    total: DEVELOPMENT_WORKFLOWS.length,
    nextCursor: null,
  };
}

export function getDevelopmentWorkflowFallback(workflowId: string): WorkflowView | undefined {
  return DEVELOPMENT_WORKFLOWS.find((workflow) => workflow.workflowId === workflowId);
}
