import type { TaskDetail, TasksSnapshot } from "./tasksTypes";

const DEVELOPMENT_TASKS: TaskDetail[] = [
  {
    id: "task-101",
    title: "Codebase Security & Vulnerability Audit",
    description: "Automated scan and deep static analysis of primary backend microservices to identify outdated packages and CVE risks.",
    status: "running",
    priority: "high",
    type: "Security Audit",
    agentId: "agent-sec-01",
    agentName: "Security Audit Agent",
    projectId: "proj-core-api",
    projectName: "Core Control Plane",
    workflowId: "wf-sec-scan",
    workflowName: "Continuous Compliance Check",
    createdAt: "2026-09-12T14:30:00Z",
    updatedAt: "2026-09-12T15:45:00Z",
    startedAt: "2026-09-12T14:32:00Z",
    dueAt: "2026-09-13T00:00:00Z",
    timeline: [
      {
        id: "tl-101-1",
        event: "Created",
        timestamp: "2026-09-12T14:30:00Z",
        status: "pending",
        details: "Task submitted via Control Plane API.",
      },
      {
        id: "tl-101-2",
        event: "Queued",
        timestamp: "2026-09-12T14:30:15Z",
        status: "queued",
        details: "Assigned to queue 'security-tasks'.",
      },
      {
        id: "tl-101-3",
        event: "Started",
        timestamp: "2026-09-12T14:32:00Z",
        status: "running",
        details: "Agent 'Security Audit Agent' accepted workload.",
      },
      {
        id: "tl-101-4",
        event: "Running",
        timestamp: "2026-09-12T15:00:00Z",
        status: "running",
        details: "Static analysis AST parsing in progress (65% completed).",
      },
    ],
    executionSummary: {
      executionId: "exec-sec-9921",
      status: "running",
      agentId: "agent-sec-01",
      agentName: "Security Audit Agent",
      duration: "1h 13m",
      startedAt: "2026-09-12T14:32:00Z",
      resultSummary: "Analysis active. 142 repositories scanned; 0 critical CVEs detected so far.",
    },
  },
  {
    id: "task-102",
    title: "Database Migration Script Generation",
    description: "Generate idempotent schema upgrade scripts for PostgreSQL v16 migration with automated rollback steps.",
    status: "completed",
    priority: "urgent",
    type: "Database Engineering",
    agentId: "agent-db-04",
    agentName: "Data Migration Specialist",
    projectId: "proj-data-infra",
    projectName: "Data Platform Infrastructure",
    workflowId: "wf-db-upgrade",
    workflowName: "Postgres 16 Migration Pipeline",
    createdAt: "2026-09-11T09:00:00Z",
    updatedAt: "2026-09-11T10:15:00Z",
    startedAt: "2026-09-11T09:02:00Z",
    completedAt: "2026-09-11T10:14:30Z",
    dueAt: "2026-09-12T12:00:00Z",
    timeline: [
      {
        id: "tl-102-1",
        event: "Created",
        timestamp: "2026-09-11T09:00:00Z",
        status: "pending",
        details: "Initiated by lead data architect.",
      },
      {
        id: "tl-102-2",
        event: "Started",
        timestamp: "2026-09-11T09:02:00Z",
        status: "running",
        details: "Assigned to 'Data Migration Specialist'.",
      },
      {
        id: "tl-102-3",
        event: "Completed",
        timestamp: "2026-09-11T10:14:30Z",
        status: "completed",
        details: "Generated SQL scripts verified against shadow staging DB.",
      },
    ],
    executionSummary: {
      executionId: "exec-db-4412",
      status: "completed",
      agentId: "agent-db-04",
      agentName: "Data Migration Specialist",
      duration: "1h 12m 30s",
      startedAt: "2026-09-11T09:02:00Z",
      completedAt: "2026-09-11T10:14:30Z",
      resultSummary: "Success. Migration scripts and rollback suite written to target repository.",
    },
  },
  {
    id: "task-103",
    title: "Customer Support Ticket Categorization",
    description: "Classify incoming L2 support tickets and extract root-cause sentiment for daily reporting.",
    status: "failed",
    priority: "medium",
    type: "NL Processing",
    agentId: "agent-nlp-02",
    agentName: "Triage & NLP Bot",
    projectId: "proj-cust-exp",
    projectName: "Customer Experience Operations",
    createdAt: "2026-09-12T08:15:00Z",
    updatedAt: "2026-09-12T08:22:00Z",
    startedAt: "2026-09-12T08:16:00Z",
    completedAt: "2026-09-12T08:22:00Z",
    timeline: [
      {
        id: "tl-103-1",
        event: "Created",
        timestamp: "2026-09-12T08:15:00Z",
        status: "pending",
        details: "Triggered by ticket webhook.",
      },
      {
        id: "tl-103-2",
        event: "Started",
        timestamp: "2026-09-12T08:16:00Z",
        status: "running",
        details: "Inference worker assigned.",
      },
      {
        id: "tl-103-3",
        event: "Failed",
        timestamp: "2026-09-12T08:22:00Z",
        status: "failed",
        details: "API rate limit exceeded during downstream LLM provider call.",
      },
    ],
    executionSummary: {
      executionId: "exec-nlp-1109",
      status: "failed",
      agentId: "agent-nlp-02",
      agentName: "Triage & NLP Bot",
      duration: "6m 0s",
      startedAt: "2026-09-12T08:16:00Z",
      completedAt: "2026-09-12T08:22:00Z",
      resultSummary: "Failure: HTTP 429 Rate Limit Exceeded from LLM Endpoint.",
    },
  },
  {
    id: "task-104",
    title: "Automated E2E Regression Testing Suite",
    description: "Execute full cross-browser playwright tests for control panel release v2.4.",
    status: "pending",
    priority: "low",
    type: "QA Automation",
    agentId: "agent-qa-07",
    agentName: "QA Automation Bot",
    projectId: "proj-ui-v2",
    projectName: "UI Control Center",
    createdAt: "2026-09-12T16:00:00Z",
    updatedAt: "2026-09-12T16:00:00Z",
    timeline: [
      {
        id: "tl-104-1",
        event: "Created",
        timestamp: "2026-09-12T16:00:00Z",
        status: "pending",
        details: "Enqueued by CI/CD pipeline build #8812.",
      },
    ],
    executionSummary: {
      executionId: "exec-qa-7731",
      status: "pending",
      agentId: "agent-qa-07",
      agentName: "QA Automation Bot",
      resultSummary: "Waiting for test runner worker slot allocation.",
    },
  },
  {
    id: "task-105",
    title: "Microservice OpenAPI Documentation Sync",
    description: "Extract updated schema definitions from Go code annotations and update developer hub.",
    status: "completed",
    priority: "low",
    type: "Documentation",
    agentId: "agent-doc-01",
    agentName: "DocSync Agent",
    projectId: "proj-core-api",
    projectName: "Core Control Plane",
    createdAt: "2026-09-10T11:00:00Z",
    updatedAt: "2026-09-10T11:20:00Z",
    startedAt: "2026-09-10T11:01:00Z",
    completedAt: "2026-09-10T11:20:00Z",
    timeline: [
      {
        id: "tl-105-1",
        event: "Created",
        timestamp: "2026-09-10T11:00:00Z",
        status: "pending",
      },
      {
        id: "tl-105-2",
        event: "Started",
        timestamp: "2026-09-10T11:01:00Z",
        status: "running",
      },
      {
        id: "tl-105-3",
        event: "Completed",
        timestamp: "2026-09-10T11:20:00Z",
        status: "completed",
      },
    ],
    executionSummary: {
      executionId: "exec-doc-3301",
      status: "completed",
      agentId: "agent-doc-01",
      agentName: "DocSync Agent",
      duration: "19m 0s",
      resultSummary: "OpenAPI specs deployed to internal developer portal.",
    },
  },
];

export function getDevelopmentTasksFallback(): TasksSnapshot {
  return {
    tasks: DEVELOPMENT_TASKS.map(({ timeline, executionSummary, ...summaryItem }) => summaryItem),
    summary: {
      total: DEVELOPMENT_TASKS.length,
      running: DEVELOPMENT_TASKS.filter((t) => t.status === "running").length,
      completed: DEVELOPMENT_TASKS.filter((t) => t.status === "completed").length,
      failed: DEVELOPMENT_TASKS.filter((t) => t.status === "failed").length,
      pending: DEVELOPMENT_TASKS.filter((t) => t.status === "pending" || t.status === "queued").length,
    },
  };
}

export function getDevelopmentTaskDetailFallback(taskId: string): TaskDetail | undefined {
  return DEVELOPMENT_TASKS.find((t) => t.id === taskId);
}

