// Control Center chunk (lazy-loaded by the router and preloaded by the splash).
export { default as AppShell } from "../../components/layout/AppShell";
export { default as OverviewPage } from "../../pages/Overview/OverviewPage";
export { default as AgentsPage } from "../../pages/Agents/AgentsPage";
export { default as AgentDetailPage } from "../../pages/Agents/AgentDetailPage";
export { default as TasksPage } from "../../pages/Tasks/TasksPage";
export { default as TaskDetailPage } from "../../pages/Tasks/TaskDetailPage";
export { default as WorkflowsPage } from "../../pages/Workflows/WorkflowsPage";
export { default as WorkflowDetailPage } from "../../pages/Workflows/WorkflowDetailPage";
export { default as DesignSystemPage } from "../../pages/DesignSystem/DesignSystemPage";
export { default as SettingsPage } from "../../pages/Settings/SettingsPage";
export { default as ProfilePage } from "../../pages/Profile/ProfilePage";
export { default as InfrastructurePage } from "../../pages/Infrastructure/InfrastructurePage";
export { default as SoftwareFactoryPage } from "../../pages/SoftwareFactory/SoftwareFactoryPage";
export { default as SoftwareFactoryProgramPage } from "../../pages/SoftwareFactory/SoftwareFactoryProgramPage";
export { default as ProjectsPage } from "../../pages/Projects/ProjectsPage";
export { default as ProjectDetailPage } from "../../pages/Projects/ProjectDetailPage";
export { default as UsersAccessPage } from "../../pages/Settings/UsersAccessPage";
export { default as ApprovalsPage } from "../../pages/Approvals/ApprovalsPage";
export { default as AuditLogPage } from "../../pages/AuditLog/AuditLogPage";
export { default as SpatialGraphPage } from "../../pages/SpatialGraph/SpatialGraphPage";
export { KnowledgePage } from '../../pages/Knowledge/KnowledgePage';
export { ExecutionFabricPage } from '../../pages/ExecutionFabric/ExecutionFabricPage';
export { default as GovernancePage } from "../../pages/Governance/GovernancePage";
export { default as CostCenterPage } from "../../pages/CostCenter/CostCenterPage";
export { default as IntelligencePage } from "../../pages/Intelligence/IntelligencePage";
export { default as IntegrationsPage } from "../../pages/Integrations/IntegrationsPage";

export { default as ExtensionsPage } from "../../pages/Extensions/ExtensionsPage";
export { default as OrganizationPage } from "../../pages/Organizations/OrganizationPage";
export { default as BillingPage } from "../../pages/Billing/BillingPage";
export { default as PlatformAdminPage } from "../../pages/Admin/PlatformAdminPage";
export { CommercialAdminPage } from "../../pages/Admin/CommercialAdminPage";
export { CustomerProfilePage } from "../../pages/CustomerOperations/CustomerProfilePage";
export { IncidentsPage } from "../../pages/CustomerOperations/IncidentsPage";
export { SsoSettingsPage } from "../../pages/Organizations/SsoSettingsPage";
export { PrivacySettingsPage } from "../../pages/Organizations/PrivacySettingsPage";
export { TrustCenterPage } from "../../pages/Trust/index.js";
export { DeveloperPlatformPage } from "../../pages/Organizations/DeveloperPlatformPage";
export { SecOpsPage } from "../../pages/Organizations/SecOpsPage";
export { MarketingPage } from "../../pages/Organizations/MarketingPage";
export { default as ContinuityPage } from "../../pages/Continuity/ContinuityPage";
export { default as ITSMPage } from "../../pages/ITSM/ITSMPage";
export { default as OperationsPage } from "../../pages/Operations/OperationsPage";
