import js from '@eslint/js'
import globals from 'globals'
import reactHooks from 'eslint-plugin-react-hooks'
import reactRefresh from 'eslint-plugin-react-refresh'
import tseslint from 'typescript-eslint'
import { defineConfig, globalIgnores } from 'eslint/config'

const reactHooksRecommended = reactHooks.configs.flat?.recommended ?? {
  plugins: { 'react-hooks': reactHooks },
  rules: reactHooks.configs.recommended.rules,
}

export default defineConfig([
  // dataconnect-generated is gitignored SDK output regenerated by Firebase tooling.
  globalIgnores(['dist', 'src/dataconnect-generated']),
  {
    files: ['**/*.{ts,tsx}'],
    extends: [
      js.configs.recommended,
      tseslint.configs.recommended,
      reactHooksRecommended,
      reactRefresh.configs.vite,
    ],
    languageOptions: {
      globals: globals.browser,
    },
  },
])
